### ISSUE TITLE
React and react-dom should be moved to peer dependencies

### ISSUE THREAD

**Issue by ankitsilaich** [moubi/swipeable-react#7]
https://github.com/moubi/swipeable-react/blob/d9e563f814e2b6400756db7ae9840340cb847630/package.json#L13

**Comment by moubi** [comment]
What I see in many packages is that `react` is both in `devDependencies` and `peerDependencies` with different versions, but not in `dependencies` at all. Have to probably figure out the min version for `peerDependencies` and test.

**Comment by moubi** [comment]
**The conclusion is:**
 - `react-dom` is only needed in tests, so it ended up in `devDependencies`
 - `react` is moved to `devDependencies` with higher version and in `peerDependencies` as min required version of `15.0.0`
 - `dependencies` is no longer present in package.json
